namespace CMT.DATAMODELS
{
    public class ObsTemplateGeneral
    {
        public int Id { get; set; }
        public int ObservationId { get; set; }
        public string? EnvironmentCondition { get; set; }
        public string? Uncertainity { get; set; }
        public int? CalibrationReviewedBy { get; set; }
        public DateTime? CalibrationReviewedDate { get; set; }
        public string? CalibrationPerformedBy { get; set; }
        public string? CalibrationPerformedDate { get; set; }
        public string? ReviewedBy { get; set; }
        public string? ReviewedDate { get; set; }
        public string? LMeasured1_1 { get; set; }
        public string? LMeasured1_2 { get; set; }
        public string? LMeasured1_3 { get; set; }
        public string? LMeasured1_4 { get; set; }
        public string? LMeasured1_5 { get; set; }
        public string? LMeasured1_6 { get; set; }
        public string? LMeasured1_7 { get; set; }
        public string? LMeasured1_8 { get; set; }
        public string? LMeasured1_9 { get; set; }
        public string? LMeasured1_10 { get; set; }
        public string? LMeasured1_11 { get; set; }
        public string? LMeasured1_12 { get; set; }
        public string? LMeasured1_13 { get; set; }
        public string? LMeasured1_14 { get; set; }
        public string? LMeasured1_15 { get; set; }
        public string? LMeasured1_16 { get; set; }
        public string? LMeasured1_17 { get; set; }
        public string? LMeasured1_18 { get; set; }
        public string? LMeasured1_19 { get; set; }
        public string? LMeasured1_20 { get; set; }
        public string? LTrial1_1 { get; set; }
        public string? LTrial1_2 { get; set; }
        public string? LTrial1_3 { get; set; }
        public string? LTrial1_4 { get; set; }
        public string? LTrial1_5 { get; set; }
        public string? LTrial1_6 { get; set; }
        public string? LTrial1_7 { get; set; }
        public string? LTrial1_8 { get; set; }
        public string? LTrial1_9 { get; set; }
        public string? LTrial1_10 { get; set; }
        public string? LTrial1_11 { get; set; }
        public string? LTrial1_12 { get; set; }
        public string? LTrial1_13 { get; set; }
        public string? LTrial1_14 { get; set; }
        public string? LTrial1_15 { get; set; }
        public string? LTrial1_16 { get; set; }
        public string? LTrial1_17 { get; set; }
        public string? LTrial1_18 { get; set; }
        public string? LTrial1_19 { get; set; }
        public string? LTrial1_20 { get; set; }
        public string? LTrial1_21 { get; set; }
        public string? LTrial1_22 { get; set; }
        public string? LTrial1_23 { get; set; }
        public string? LTrial1_24 { get; set; }
        public string? LTrial1_25 { get; set; }
        public string? LTrial1_26 { get; set; }
        public string? LTrial1_27 { get; set; }
        public string? LTrial1_28 { get; set; }
        public string? LTrial1_29 { get; set; }
        public string? LTrial1_30 { get; set; }
        public string? LTrial1_31 { get; set; }
        public string? LTrial1_32 { get; set; }
        public string? LTrial1_33 { get; set; }
        public string? LTrial1_34 { get; set; }
        public string? LTrial1_35 { get; set; }
        public string? LTrial1_36 { get; set; }
        public string? LTrial1_37 { get; set; }
        public string? LTrial1_38 { get; set; }
        public string? LTrial1_39 { get; set; }
        public string? LTrial1_40 { get; set; }
        public string? LTrial1_41 { get; set; }
        public string? LTrial1_42 { get; set; }
        public string? LTrial1_43 { get; set; }
        public string? LTrial1_44 { get; set; }
        public string? LTrial1_45 { get; set; }
        public string? LTrial1_46 { get; set; }
        public string? LTrial1_47 { get; set; }
        public string? LTrial1_48 { get; set; }
        public string? LTrial1_49 { get; set; }
        public string? LTrial1_50 { get; set; }
        public string? LTrial1_51 { get; set; }
        public string? LTrial1_52 { get; set; }
        public string? LTrial1_53 { get; set; }
        public string? LTrial1_54 { get; set; }
        public string? LTrial1_55 { get; set; }
        public string? LTrial1_56 { get; set; }
        public string? LTrial1_57 { get; set; }
        public string? LTrial1_58 { get; set; }
        public string? LTrial1_59 { get; set; }
        public string? LTrial1_60 { get; set; }
        public string? LMeasured2_1 { get; set; }
        public string? LMeasured2_2 { get; set; }
        public string? LMeasured2_3 { get; set; }
        public string? LMeasured2_4 { get; set; }
        public string? LMeasured2_5 { get; set; }
        public string? LMeasured2_6 { get; set; }
        public string? LMeasured2_7 { get; set; }
        public string? LMeasured2_8 { get; set; }
        public string? LMeasured2_9 { get; set; }
        public string? LMeasured2_10 { get; set; }
        public string? LMeasured2_11 { get; set; }
        public string? LMeasured2_12 { get; set; }
        public string? LMeasured2_13 { get; set; }
        public string? LMeasured2_14 { get; set; }
        public string? LMeasured2_15 { get; set; }
        public string? LMeasured2_16 { get; set; }
        public string? LMeasured2_17 { get; set; }
        public string? LMeasured2_18 { get; set; }
        public string? LMeasured2_19 { get; set; }
        public string? LMeasured2_20 { get; set; }
        public string? LTrial2_1 { get; set; }
        public string? LTrial2_2 { get; set; }
        public string? LTrial2_3 { get; set; }
        public string? LTrial2_4 { get; set; }
        public string? LTrial2_5 { get; set; }
        public string? LTrial2_6 { get; set; }
        public string? LTrial2_7 { get; set; }
        public string? LTrial2_8 { get; set; }
        public string? LTrial2_9 { get; set; }
        public string? LTrial2_10 { get; set; }
        public string? LTrial2_11 { get; set; }
        public string? LTrial2_12 { get; set; }
        public string? LTrial2_13 { get; set; }
        public string? LTrial2_14 { get; set; }
        public string? LTrial2_15 { get; set; }
        public string? LTrial2_16 { get; set; }
        public string? LTrial2_17 { get; set; }
        public string? LTrial2_18 { get; set; }
        public string? LTrial2_19 { get; set; }
        public string? LTrial2_20 { get; set; }
        public string? LTrial2_21 { get; set; }
        public string? LTrial2_22 { get; set; }
        public string? LTrial2_23 { get; set; }
        public string? LTrial2_24 { get; set; }
        public string? LTrial2_25 { get; set; }
        public string? LTrial2_26 { get; set; }
        public string? LTrial2_27 { get; set; }
        public string? LTrial2_28 { get; set; }
        public string? LTrial2_29 { get; set; }
        public string? LTrial2_30 { get; set; }
        public string? LTrial2_31 { get; set; }
        public string? LTrial2_32 { get; set; }
        public string? LTrial2_33 { get; set; }
        public string? LTrial2_34 { get; set; }
        public string? LTrial2_35 { get; set; }
        public string? LTrial2_36 { get; set; }
        public string? LTrial2_37 { get; set; }
        public string? LTrial2_38 { get; set; }
        public string? LTrial2_39 { get; set; }
        public string? LTrial2_40 { get; set; }
        public string? LTrial2_41 { get; set; }
        public string? LTrial2_42 { get; set; }
        public string? LTrial2_43 { get; set; }
        public string? LTrial2_44 { get; set; }
        public string? LTrial2_45 { get; set; }
        public string? LTrial2_46 { get; set; }
        public string? LTrial2_47 { get; set; }
        public string? LTrial2_48 { get; set; }
        public string? LTrial2_49 { get; set; }
        public string? LTrial2_50 { get; set; }
        public string? LTrial2_51 { get; set; }
        public string? LTrial2_52 { get; set; }
        public string? LTrial2_53 { get; set; }
        public string? LTrial2_54 { get; set; }
        public string? LTrial2_55 { get; set; }
        public string? LTrial2_56 { get; set; }
        public string? LTrial2_57 { get; set; }
        public string? LTrial2_58 { get; set; }
        public string? LTrial2_59 { get; set; }
        public string? LTrial2_60 { get; set; }
        public string? LMeasured3_1 { get; set; }
        public string? LMeasured3_2 { get; set; }
        public string? LMeasured3_3 { get; set; }
        public string? LMeasured3_4 { get; set; }
        public string? LMeasured3_5 { get; set; }
        public string? LMeasured3_6 { get; set; }
        public string? LMeasured3_7 { get; set; }
        public string? LMeasured3_8 { get; set; }
        public string? LMeasured3_9 { get; set; }
        public string? LMeasured3_10 { get; set; }
        public string? LMeasured3_11 { get; set; }
        public string? LMeasured3_12 { get; set; }
        public string? LMeasured3_13 { get; set; }
        public string? LMeasured3_14 { get; set; }
        public string? LMeasured3_15 { get; set; }
        public string? LMeasured3_16 { get; set; }
        public string? LMeasured3_17 { get; set; }
        public string? LMeasured3_18 { get; set; }
        public string? LMeasured3_19 { get; set; }
        public string? LMeasured3_20 { get; set; }
        public string? LTrial3_1 { get; set; }
        public string? LTrial3_2 { get; set; }
        public string? LTrial3_3 { get; set; }
        public string? LTrial3_4 { get; set; }
        public string? LTrial3_5 { get; set; }
        public string? LTrial3_6 { get; set; }
        public string? LTrial3_7 { get; set; }
        public string? LTrial3_8 { get; set; }
        public string? LTrial3_9 { get; set; }
        public string? LTrial3_10 { get; set; }
        public string? LTrial3_11 { get; set; }
        public string? LTrial3_12 { get; set; }
        public string? LTrial3_13 { get; set; }
        public string? LTrial3_14 { get; set; }
        public string? LTrial3_15 { get; set; }
        public string? LTrial3_16 { get; set; }
        public string? LTrial3_17 { get; set; }
        public string? LTrial3_18 { get; set; }
        public string? LTrial3_19 { get; set; }
        public string? LTrial3_20 { get; set; }
        public string? LTrial3_21 { get; set; }
        public string? LTrial3_22 { get; set; }
        public string? LTrial3_23 { get; set; }
        public string? LTrial3_24 { get; set; }
        public string? LTrial3_25 { get; set; }
        public string? LTrial3_26 { get; set; }
        public string? LTrial3_27 { get; set; }
        public string? LTrial3_28 { get; set; }
        public string? LTrial3_29 { get; set; }
        public string? LTrial3_30 { get; set; }
        public string? LTrial3_31 { get; set; }
        public string? LTrial3_32 { get; set; }
        public string? LTrial3_33 { get; set; }
        public string? LTrial3_34 { get; set; }
        public string? LTrial3_35 { get; set; }
        public string? LTrial3_36 { get; set; }
        public string? LTrial3_37 { get; set; }
        public string? LTrial3_38 { get; set; }
        public string? LTrial3_39 { get; set; }
        public string? LTrial3_40 { get; set; }
        public string? LTrial3_41 { get; set; }
        public string? LTrial3_42 { get; set; }
        public string? LTrial3_43 { get; set; }
        public string? LTrial3_44 { get; set; }
        public string? LTrial3_45 { get; set; }
        public string? LTrial3_46 { get; set; }
        public string? LTrial3_47 { get; set; }
        public string? LTrial3_48 { get; set; }
        public string? LTrial3_49 { get; set; }
        public string? LTrial3_50 { get; set; }
        public string? LTrial3_51 { get; set; }
        public string? LTrial3_52 { get; set; }
        public string? LTrial3_53 { get; set; }
        public string? LTrial3_54 { get; set; }
        public string? LTrial3_55 { get; set; }
        public string? LTrial3_56 { get; set; }
        public string? LTrial3_57 { get; set; }
        public string? LTrial3_58 { get; set; }
        public string? LTrial3_59 { get; set; }
        public string? LTrial3_60 { get; set; }
        public string? LMeasured4_1 { get; set; }
        public string? LMeasured4_2 { get; set; }
        public string? LMeasured4_3 { get; set; }
        public string? LMeasured4_4 { get; set; }
        public string? LMeasured4_5 { get; set; }
        public string? LMeasured4_6 { get; set; }
        public string? LMeasured4_7 { get; set; }
        public string? LMeasured4_8 { get; set; }
        public string? LMeasured4_9 { get; set; }
        public string? LMeasured4_10 { get; set; }
        public string? LMeasured4_11 { get; set; }
        public string? LMeasured4_12 { get; set; }
        public string? LMeasured4_13 { get; set; }
        public string? LMeasured4_14 { get; set; }
        public string? LMeasured4_15 { get; set; }
        public string? LMeasured4_16 { get; set; }
        public string? LMeasured4_17 { get; set; }
        public string? LMeasured4_18 { get; set; }
        public string? LMeasured4_19 { get; set; }
        public string? LMeasured4_20 { get; set; }
        public string? LTrial4_1 { get; set; }
        public string? LTrial4_2 { get; set; }
        public string? LTrial4_3 { get; set; }
        public string? LTrial4_4 { get; set; }
        public string? LTrial4_5 { get; set; }
        public string? LTrial4_6 { get; set; }
        public string? LTrial4_7 { get; set; }
        public string? LTrial4_8 { get; set; }
        public string? LTrial4_9 { get; set; }
        public string? LTrial4_10 { get; set; }
        public string? LTrial4_11 { get; set; }
        public string? LTrial4_12 { get; set; }
        public string? LTrial4_13 { get; set; }
        public string? LTrial4_14 { get; set; }
        public string? LTrial4_15 { get; set; }
        public string? LTrial4_16 { get; set; }
        public string? LTrial4_17 { get; set; }
        public string? LTrial4_18 { get; set; }
        public string? LTrial4_19 { get; set; }
        public string? LTrial4_20 { get; set; }
        public string? LTrial4_21 { get; set; }
        public string? LTrial4_22 { get; set; }
        public string? LTrial4_23 { get; set; }
        public string? LTrial4_24 { get; set; }
        public string? LTrial4_25 { get; set; }
        public string? LTrial4_26 { get; set; }
        public string? LTrial4_27 { get; set; }
        public string? LTrial4_28 { get; set; }
        public string? LTrial4_29 { get; set; }
        public string? LTrial4_30 { get; set; }
        public string? LTrial4_31 { get; set; }
        public string? LTrial4_32 { get; set; }
        public string? LTrial4_33 { get; set; }
        public string? LTrial4_34 { get; set; }
        public string? LTrial4_35 { get; set; }
        public string? LTrial4_36 { get; set; }
        public string? LTrial4_37 { get; set; }
        public string? LTrial4_38 { get; set; }
        public string? LTrial4_39 { get; set; }
        public string? LTrial4_40 { get; set; }
        public string? LTrial4_41 { get; set; }
        public string? LTrial4_42 { get; set; }
        public string? LTrial4_43 { get; set; }
        public string? LTrial4_44 { get; set; }
        public string? LTrial4_45 { get; set; }
        public string? LTrial4_46 { get; set; }
        public string? LTrial4_47 { get; set; }
        public string? LTrial4_48 { get; set; }
        public string? LTrial4_49 { get; set; }
        public string? LTrial4_50 { get; set; }
        public string? LTrial4_51 { get; set; }
        public string? LTrial4_52 { get; set; }
        public string? LTrial4_53 { get; set; }
        public string? LTrial4_54 { get; set; }
        public string? LTrial4_55 { get; set; }
        public string? LTrial4_56 { get; set; }
        public string? LTrial4_57 { get; set; }
        public string? LTrial4_58 { get; set; }
        public string? LTrial4_59 { get; set; }
        public string? LTrial4_60 { get; set; }
        public string? Repeatability1_1 { get; set; }
        public string? Repeatability1_2 { get; set; }
        public string? Repeatability1_3 { get; set; }
        public string? Repeatability1_4 { get; set; }
        public string? Repeatability1_5 { get; set; }
        public string? Repeatability2_1 { get; set; }
        public string? Repeatability2_2 { get; set; }
        public string? Repeatability2_3 { get; set; }
        public string? Repeatability2_4 { get; set; }
        public string? Repeatability2_5 { get; set; }
        public DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public virtual TemplateObservation Observation{get;set;}
        public string? Remarks { get; set; }
        public string? CalibrationResult { get; set; }
    }
}