namespace CMT.DATAMODELS
{
    public class ObsTemplateVernierCaliper
    {
        public int Id { get; set; }
        public int? ObservationId { get; set; }
        public string? EnvironmentCondition { get; set; }
        public string? Uncertainity { get; set; }

        public string? CalibrationResult{get;set;}
        public string? Remarks{get;set;}

        public int? CalibrationReviewedBy { get; set; }
        public DateTime CalibrationReviewedDate { get; set; }
        public DateTime CreatedOn { get; set; }
        public int? CreatedBy { get; set; }
        public string? Measured1_1 { get; set; }
        public string? Actuals1_T_1 { get; set; }
        public string? Actuals1_T_2 { get; set; }
        public string? Actuals1_T_3 { get; set; }
        public string? Avg1_1 { get; set; }
        public string? Measured1_2 { get; set; }
        public string? Actuals1_T_4 { get; set; }
        public string? Actuals1_T_5 { get; set; }
        public string? Actuals1_T_6 { get; set; }
        public string? Avg1_2 { get; set; }
        public string? Measured1_3 { get; set; }
        public string? Actuals1_T_7 { get; set; }
        public string? Actuals1_T_8 { get; set; }
        public string? Actuals1_T_9 { get; set; }
        public string? Avg1_3 { get; set; }
        public string? Measured1_4 { get; set; }
        public string? Actuals1_T_10 { get; set; }
        public string? Actuals1_T_11 { get; set; }
        public string? Actuals1_T_12 { get; set; }
        public string? Avg1_4 { get; set; }
        public string? Measured1_5 { get; set; }
        public string? Actuals1_T_13 { get; set; }
        public string? Actuals1_T_14 { get; set; }
        public string? Actuals1_T_15 { get; set; }
        public string? Avg1_5 { get; set; }
        public string? Measured2_1 { get; set; }
        public string? Actuals2_T_1 { get; set; }
        public string? Actuals2_T_2 { get; set; }
        public string? Actuals2_T_3 { get; set; }
        public string? Avg2_1 { get; set; }
        public string? Measured2_2 { get; set; }
        public string? Actuals2_T_4 { get; set; }
        public string? Actuals2_T_5 { get; set; }
        public string? Actuals2_T_6 { get; set; }
        public string? Avg2_2 { get; set; }
        public string? Measured2_3 { get; set; }
        public string? Actuals2_T_7 { get; set; }
        public string? Actuals2_T_8 { get; set; }
        public string? Actuals2_T_9 { get; set; }
        public string? Avg2_3 { get; set; }
        public string? Measured2_4 { get; set; }
        public string? Actuals2_T_10 { get; set; }
        public string? Actuals2_T_11 { get; set; }
        public string? Actuals2_T_12 { get; set; }
        public string? Avg2_4 { get; set; }
        public string? Measured2_5 { get; set; }
        public string? Actuals2_T_13 { get; set; }
        public string? Actuals2_T_14 { get; set; }
        public string? Actuals2_T_15 { get; set; }
        public string? Avg2_5 { get; set; }
        public string? Measured3_1 { get; set; }
        public string? Actuals3_T_1 { get; set; }
        public string? Actuals3_T_2 { get; set; }
        public string? Actuals3_T_3 { get; set; }
        public string? Avg3_1 { get; set; }
        public string? Measured3_2 { get; set; }
        public string? Actuals3_T_4 { get; set; }
        public string? Actuals3_T_5 { get; set; }
        public string? Actuals3_T_6 { get; set; }
        public string? Avg3_2 { get; set; }
        public string? Measured3_3 { get; set; }
        public string? Actuals3_T_7 { get; set; }
        public string? Actuals3_T_8 { get; set; }
        public string? Actuals3_T_9 { get; set; }
        public string? Avg3_3 { get; set; }
        public string? Measured3_4 { get; set; }
        public string? Actuals3_T_10 { get; set; }
        public string? Actuals3_T_11 { get; set; }
        public string? Actuals3_T_12 { get; set; }
        public string? Avg3_4 { get; set; }
        public string? Measured3_5 { get; set; }
        public string? Actuals3_T_13 { get; set; }
        public string? Actuals3_T_14 { get; set; }
        public string? Actuals3_T_15 { get; set; }
        public string? Avg3_5 { get; set; }
        public string? Measured4_1 { get; set; }
        public string? Actuals4_T_1 { get; set; }
        public string? Actuals4_T_2 { get; set; }
        public string? Actuals4_T_3 { get; set; }
        public string? Avg4_1 { get; set; }
        public string? Measured4_2 { get; set; }
        public string? Actuals4_T_4 { get; set; }
        public string? Actuals4_T_5 { get; set; }
        public string? Actuals4_T_6 { get; set; }
        public string? Avg4_2 { get; set; }
        public string? Measured4_3 { get; set; }
        public string? Actuals4_T_7 { get; set; }
        public string? Actuals4_T_8 { get; set; }
        public string? Actuals4_T_9 { get; set; }
        public string? Avg4_3 { get; set; }
        public string? Measured4_4 { get; set; }
        public string? Actuals4_T_10 { get; set; }
        public string? Actuals4_T_11 { get; set; }
        public string? Actuals4_T_12 { get; set; }
        public string? Avg4_4 { get; set; }
        public string? Measured4_5 { get; set; }
        public string? Actuals4_T_13 { get; set; }
        public string? Actuals4_T_14 { get; set; }
        public string? Actuals4_T_15 { get; set; }
        public string? Avg4_5 { get; set; }
        public string? Measured5_1 { get; set; }
        public string? Actuals5_T_1 { get; set; }
        public string? Actuals5_T_2 { get; set; }
        public string? Actuals5_T_3 { get; set; }
        public string? Avg5_1 { get; set; }
        public string? Measured5_2 { get; set; }
        public string? Actuals5_T_4 { get; set; }
        public string? Actuals5_T_5 { get; set; }
        public string? Actuals5_T_6 { get; set; }
        public string? Avg5_2 { get; set; }
        public string? Measured5_3 { get; set; }
        public string? Actuals5_T_7 { get; set; }
        public string? Actuals5_T_8 { get; set; }
        public string? Actuals5_T_9 { get; set; }
        public string? Avg5_3 { get; set; }
        public string? Measured5_4 { get; set; }
        public string? Actuals5_T_10 { get; set; }
        public string? Actuals5_T_11 { get; set; }
        public string? Actuals5_T_12 { get; set; }
        public string? Avg5_4 { get; set; }
        public string? Measured5_5 { get; set; }
        public string? Actuals5_T_13 { get; set; }
        public string? Actuals5_T_14 { get; set; }
        public string? Actuals5_T_15 { get; set; }
        public string? Avg5_5 { get; set; }
        public string? Measured6_1 { get; set; }
        public string? Actuals6_T_1 { get; set; }
        public string? Actuals6_T_2 { get; set; }
        public string? Actuals6_T_3 { get; set; }
        public string? Avg6_1 { get; set; }
        public string? Measured6_2 { get; set; }
        public string? Actuals6_T_4 { get; set; }
        public string? Actuals6_T_5 { get; set; }
        public string? Actuals6_T_6 { get; set; }
        public string? Avg6_2 { get; set; }
        public string? Measured6_3 { get; set; }
        public string? Actuals6_T_7 { get; set; }
        public string? Actuals6_T_8 { get; set; }
        public string? Actuals6_T_9 { get; set; }
        public string? Avg6_3 { get; set; }
        public string? Measured6_4 { get; set; }
        public string? Actuals6_T_10 { get; set; }
        public string? Actuals6_T_11 { get; set; }
        public string? Actuals6_T_12 { get; set; }
        public string? Avg6_4 { get; set; }
        public string? Measured6_5 { get; set; }
        public string? Actuals6_T_13 { get; set; }
        public string? Actuals6_T_14 { get; set; }
        public string? Actuals6_T_15 { get; set; }
        public string? Avg6_5 { get; set; }
        public string? MuLeftValue1 { get; set; }
        public string? MuRightValue1 { get; set; }
        public string? MuLeftValue2 { get; set; }
        public string? MuRightValue2 { get; set; }
        public string? MuLeftValue3 { get; set; }
        public string? MuRightValue3 { get; set; }
        public string? MuLeftValue4 { get; set; }
        public string? MuRightValue4 { get; set; }
        public string? MuLeftValue5 { get; set; }
        public string? MuRightValue5 { get; set; }
        public string? CalibrationPerformedBy { get; set; }
        public string? ReviewedBy { get; set; }

        public string? ExternalParallelismDetails { get; set; }
               
        public string? InternaljawParallelismDetails { get; set; }
        public string? CalibrationPerformedDate { get; set; }
        public string? ReviewedDate { get; set; }

        public virtual TemplateObservation Observation{get;set;}
    }
}